CC = gcc
CFLAGS = -Wall -Wextra -pedantic -std=c99

.PHONY: all clean

all: block_cipher

all: block_cipher

block_cipher: block_cipher.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm -f block_cipher *.o a.out
